/** Public renderer construction contract. Implementation helpers remain package-private. */
export {
  definePortableVertexSemantic,
  assertPortableResource,
  type PortableComponentType,
  type PortableTopology,
  type PortableTextureFormat,
  portableTextureFormats,
  type PortableCustomVertexSemantic,
  type PortableVertexSemantic,
  portableResourceKinds,
  portableTopologies,
  type PortableBufferView,
  type PortableAccessor,
  type PortableVertexAttribute,
  type PortableVertexInput,
  type PortableGeometryIndices,
  type PortableDrawRange,
  type PortableBufferPayload,
  type PortableTexturePayload,
  type PortableTextureArrayPayload,
  type PortableGeometryPayload,
  type PortableLeafResource,
  type PortableResourceGroupPayload,
  type PortableResource,
  type PortableResourceKind,
} from '../internal/resources.js';
