/** Public renderer construction contract. Implementation helpers remain package-private. */
export {
  defineCodecBuffers,
  defineTechniqueSchema,
  defineTechniqueGeometryKind,
  schemaCodecBuffers,
  type CodecScalarKind,
  type CodecBufferDeclaration,
  type CodecBufferDeclarations,
  type TechniqueBindingDeclaration,
  type TechniqueBufferResourceDeclaration,
  type TechniqueTextureResourceDeclaration,
  type TechniqueTextureArrayResourceDeclaration,
  type TechniqueGeometryResourceDeclaration,
  type TechniqueResourceGroupMembers,
  type TechniqueResourceGroupDeclaration,
  type TechniqueResourceDeclaration,
  type TechniqueResourceDeclarations,
  type TechniqueCustomGeometryKind,
  type TechniqueGeometryKind,
  type TechniqueSuppliedGeometryKind,
  type TechniqueGeometryCoordinates,
  type TechniqueGeometryDeclaration,
  type TechniqueRenderDeclaration,
  type TechniqueSchemaDeclaration,
  type TechniqueSchema,
  type TechniqueSchemaMetadata,
} from '../internal/schema.js';
